<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $category['name'] ?? 'Category Price List' }}</title>
    <style>
        @page {
            size: A4 landscape;
            margin: 22px 18px;
        }
        body {
            margin: 0;
            color: #0f172a;
            font-family: Arial, Helvetica, sans-serif;
            font-size: 11px;
        }
        .header {
            margin-bottom: 14px;
        }
        .title {
            margin: 0;
            font-size: 20px;
            font-weight: 700;
        }
        .meta {
            margin-top: 6px;
            color: #475569;
            font-size: 10px;
        }
        .meta span {
            margin-right: 14px;
        }
        .summary {
            margin-top: 10px;
            padding: 8px 10px;
            border: 1px solid #cbd5e1;
            background: #f8fafc;
            font-size: 10px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            table-layout: fixed;
        }
        thead {
            display: table-header-group;
        }
        th, td {
            border: 1px solid #cbd5e1;
            padding: 8px;
            vertical-align: middle;
        }
        th {
            background: #e2e8f0;
            font-size: 10px;
            font-weight: 700;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            text-align: left;
        }
        tbody tr:nth-child(even) {
            background: #f8fafc;
        }
        .picture-col {
            width: 12%;
        }
        .product-col {
            width: 28%;
        }
        .variant-col {
            width: 32%;
        }
        .qty-col {
            width: 12%;
            text-align: center;
        }
        .price-col {
            width: 16%;
            text-align: right;
        }
        .thumb {
            width: 56px;
            height: 56px;
            border: 1px solid #cbd5e1;
            border-radius: 8px;
            object-fit: cover;
            display: block;
            margin: 0 auto;
        }
        .product-name {
            font-weight: 700;
            line-height: 1.35;
        }
        .variant-name {
            font-weight: 600;
            line-height: 1.35;
        }
        .variant-meta {
            margin-top: 4px;
            color: #475569;
            font-size: 10px;
        }
        .qty-value {
            font-weight: 700;
            font-size: 13px;
        }
        .price-value {
            font-weight: 700;
            font-size: 13px;
        }
        .price-original {
            margin-bottom: 4px;
            color: #64748b;
            font-size: 10px;
            text-decoration: line-through;
        }
        .discount-badge {
            display: inline-block;
            margin-bottom: 5px;
            padding: 2px 7px;
            border-radius: 999px;
            background: #fee2e2;
            color: #be123c;
            font-size: 9px;
            font-weight: 700;
        }
        .empty-state {
            padding: 18px;
            text-align: center;
            color: #475569;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1 class="title">{{ $category['name'] ?? 'Category Price List' }}</h1>
        <div class="meta">
            <span>Generated: {{ optional($generated_at)->format('F j, Y g:i A') }}</span>
            @if (!empty($generated_by))
                <span>Generated by: {{ $generated_by }}</span>
            @endif
        </div>
        <div class="summary">
            <strong>Total rows:</strong> {{ $summary['total_rows'] ?? 0 }}
            <span style="margin-left: 14px;"><strong>Sort:</strong> {{ $summary['sort_label'] ?? 'Default' }}</span>
            <span style="margin-left: 14px;"><strong>Scope:</strong> {{ !empty($summary['in_stock_only']) ? 'In-stock only' : 'All active variants' }}</span>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th class="picture-col">Product Picture</th>
                <th class="product-col">Product Name</th>
                <th class="variant-col">Product Variant</th>
                <th class="qty-col">Quantity Available</th>
                <th class="price-col">Sales Price</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($rows as $row)
                <tr>
                    <td class="picture-col">
                        <img class="thumb" src="{{ $row['image_pdf_src'] }}" alt="Product image">
                    </td>
                    <td class="product-col">
                        <div class="product-name">{{ $row['product_name'] }}</div>
                    </td>
                    <td class="variant-col">
                        <div class="variant-name">{{ $row['variant_name'] }}</div>
                        @if (!empty($row['sku']))
                            <div class="variant-meta">SKU: {{ $row['sku'] }}</div>
                        @endif
                    </td>
                    <td class="qty-col">
                        <div class="qty-value">{{ number_format((int) $row['quantity_available']) }}</div>
                    </td>
                    <td class="price-col">
                        @if (!empty($row['has_active_discount']) && (float) ($row['original_price'] ?? 0) > (float) ($row['final_price'] ?? 0))
                            @if (!empty($row['discount_display_label']))
                                <div class="discount-badge">{{ $row['discount_display_label'] }}</div>
                            @endif
                            <div class="price-original">N{{ number_format((float) $row['original_price'], 2) }}</div>
                        @endif
                        <div class="price-value">N{{ number_format((float) ($row['final_price'] ?? $row['sales_price']), 2) }}</div>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="5" class="empty-state">
                        No active product variants matched the selected category and filters.
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>
