<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Inventory Valuation Summary</title>
    <style>
        @page {
            size: A4 landscape;
            margin: 18px 16px;
        }
        body {
            margin: 0;
            color: #111827;
            font-family: DejaVu Sans, Arial, Helvetica, sans-serif;
            font-size: 11px;
        }
        .header {
            text-align: center;
            margin-bottom: 12px;
        }
        .company {
            font-size: 12px;
            font-weight: 700;
            margin-bottom: 2px;
        }
        .title {
            margin: 0;
            font-size: 20px;
            font-weight: 700;
        }
        .subtitle {
            margin-top: 4px;
            font-size: 11px;
            color: #334155;
        }
        .meta {
            margin-top: 4px;
            font-size: 10px;
            color: #475569;
        }
        .summary {
            margin: 10px 0 14px;
            padding: 8px 10px;
            border: 1px solid #cbd5e1;
            background: #f8fafc;
            font-size: 10px;
        }
        .summary span {
            margin-right: 12px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            table-layout: fixed;
        }
        thead {
            display: table-header-group;
        }
        th, td {
            border: 1px solid #dbe3ee;
            padding: 5px 6px;
            vertical-align: top;
        }
        th {
            background: #e5e7eb;
            font-size: 10px;
            font-weight: 700;
            text-transform: uppercase;
            letter-spacing: 0.04em;
        }
        .category-row td {
            background: #d1d5db;
            font-weight: 700;
            text-transform: uppercase;
            letter-spacing: 0.04em;
        }
        .subtotal-row td {
            background: #eef2f7;
            font-weight: 700;
        }
        .grand-total td {
            background: #e2e8f0;
            font-weight: 700;
            font-size: 12px;
        }
        .text-right {
            text-align: right;
        }
        .variant {
            font-weight: 600;
            line-height: 1.35;
        }
        .sku {
            margin-top: 2px;
            font-size: 10px;
            color: #64748b;
        }
        .empty {
            padding: 18px;
            text-align: center;
            color: #475569;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="company">{{ config('app.name') }}</div>
        <h1 class="title">Inventory Valuation Summary</h1>
        <div class="subtitle">As of {{ $summary['as_of_label'] ?? optional($generated_at)->format('F j, Y') }}</div>
        <div class="meta">
            @if(!empty($selected_category['name']))
                Scope: {{ $selected_category['name'] }} |
            @endif
            @if(!empty($generated_by))
                Generated by: {{ $generated_by }} |
            @endif
            Generated: {{ optional($generated_at)->format('F j, Y g:i A') }}
        </div>
    </div>

    <div class="summary">
        <span><strong>Total On Hand:</strong> {{ number_format((int) ($summary['total_on_hand'] ?? 0)) }}</span>
        <span><strong>Total Asset Value:</strong> &#8358;{{ number_format((float) ($summary['total_asset_value'] ?? 0), 2) }}</span>
        <span><strong>Total Retail Value:</strong> &#8358;{{ number_format((float) ($summary['total_retail_value'] ?? 0), 2) }}</span>
        <span><strong>Categories:</strong> {{ number_format((int) ($summary['category_count'] ?? 0)) }}</span>
        <span><strong>Variants:</strong> {{ number_format((int) ($summary['variant_count'] ?? 0)) }}</span>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 40%;">Variant</th>
                <th class="text-right" style="width: 7%;">On Hand</th>
                <th class="text-right" style="width: 11%;">Avg Cost</th>
                <th class="text-right" style="width: 12%;">Asset Value</th>
                <th class="text-right" style="width: 8%;">% Asset</th>
                <th class="text-right" style="width: 11%;">Sale Price</th>
                <th class="text-right" style="width: 12%;">Retail Value</th>
                <th class="text-right" style="width: 8%;">% Retail</th>
            </tr>
        </thead>
        <tbody>
            @forelse($groups as $group)
                <tr class="category-row">
                    <td colspan="8">{{ $group['category_name'] }}</td>
                </tr>

                @foreach($group['rows'] as $row)
                    <tr>
                        <td>
                            <div class="variant">{{ $row['variant_name'] }}</div>
                            @if(!empty($row['sku']))
                                <div class="sku">SKU: {{ $row['sku'] }}</div>
                            @endif
                        </td>
                        <td class="text-right">{{ number_format((int) $row['on_hand']) }}</td>
                        <td class="text-right">&#8358;{{ number_format((float) $row['average_cost'], 2) }}</td>
                        <td class="text-right">&#8358;{{ number_format((float) $row['asset_value'], 2) }}</td>
                        <td class="text-right">{{ number_format((float) $row['asset_percent'], 1) }}%</td>
                        <td class="text-right">&#8358;{{ number_format((float) $row['sale_price'], 2) }}</td>
                        <td class="text-right">&#8358;{{ number_format((float) $row['retail_value'], 2) }}</td>
                        <td class="text-right">{{ number_format((float) $row['retail_percent'], 1) }}%</td>
                    </tr>
                @endforeach

                <tr class="subtotal-row">
                    <td>Total {{ $group['category_name'] }}</td>
                    <td class="text-right">{{ number_format((int) $group['totals']['on_hand']) }}</td>
                    <td></td>
                    <td class="text-right">&#8358;{{ number_format((float) $group['totals']['asset_value'], 2) }}</td>
                    <td class="text-right">{{ number_format((float) $group['totals']['asset_percent'], 1) }}%</td>
                    <td></td>
                    <td class="text-right">&#8358;{{ number_format((float) $group['totals']['retail_value'], 2) }}</td>
                    <td class="text-right">{{ number_format((float) $group['totals']['retail_percent'], 1) }}%</td>
                </tr>
            @empty
                <tr>
                    <td colspan="8" class="empty">No stocked inventory matched the selected filters.</td>
                </tr>
            @endforelse
        </tbody>

        @if(!empty($groups))
            <tfoot>
                <tr class="grand-total">
                    <td>TOTAL</td>
                    <td class="text-right">{{ number_format((int) ($summary['total_on_hand'] ?? 0)) }}</td>
                    <td></td>
                    <td class="text-right">&#8358;{{ number_format((float) ($summary['total_asset_value'] ?? 0), 2) }}</td>
                    <td class="text-right">100.0%</td>
                    <td></td>
                    <td class="text-right">&#8358;{{ number_format((float) ($summary['total_retail_value'] ?? 0), 2) }}</td>
                    <td class="text-right">100.0%</td>
                </tr>
            </tfoot>
        @endif
    </table>
</body>
</html>
