<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Wallet Balances Report</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #0f172a; font-size: 12px; }
        .header { margin-bottom: 24px; }
        .title { font-size: 22px; font-weight: 700; margin-bottom: 6px; }
        .muted { color: #475569; }
        .summary { width: 100%; border-collapse: collapse; margin-top: 18px; }
        .summary th, .summary td { border: 1px solid #cbd5e1; padding: 10px 12px; }
        .summary th { background: #f8fafc; text-align: left; font-size: 11px; text-transform: uppercase; }
        .right { text-align: right; }
        .pill { display: inline-block; padding: 6px 10px; background: #e2e8f0; border-radius: 999px; margin-right: 8px; }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">Wallet Balances Report</div>
        <div class="muted">
            Branch: {{ data_get($summary, 'selected_branch.name', 'All branches') }}
            @if(data_get($summary, 'selected_branch.code'))
                ({{ data_get($summary, 'selected_branch.code') }})
            @endif
        </div>
        <div class="muted">Generated: {{ $generated_at->format('d M Y, h:i A') }}</div>
        @if($generated_by)
            <div class="muted">Generated by: {{ $generated_by }}</div>
        @endif

        <div style="margin-top: 16px;">
            <span class="pill">{{ number_format((int) data_get($summary, 'total_active_accounts', 0)) }} active accounts</span>
            <span class="pill">NGN {{ number_format((float) data_get($summary, 'total_balance', 0), 2) }} total balance</span>
        </div>
    </div>

    <table class="summary">
        <thead>
            <tr>
                <th>Wallet Category</th>
                <th>Active Accounts</th>
                <th class="right">Current Balance</th>
            </tr>
        </thead>
        <tbody>
            @foreach($rows as $row)
                <tr>
                    <td>{{ $row['label'] }}</td>
                    <td>{{ number_format((int) $row['active_accounts']) }}</td>
                    <td class="right">NGN {{ number_format((float) $row['total_balance'], 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
</body>
</html>
